services:
  nacos:
    ports: !reset []

  sentinel:
    ports: !reset []

  postgres:
    ports: !reset []

  redis:
    ports: !reset []

  user-service:
    ports: !reset []

  course-service:
    ports: !reset []

  homework-service:
    ports: !reset []

  progress-service:
    ports: !reset []

  minio:
    ports: !reset []

  prometheus:
    ports: !reset []

  grafana:
    ports: !reset []

  jaeger:
    ports: !reset []
